<ol class="breadcrumb breadcrumb-top">
  <li><a href="<?php echo BASE_URL; ?>"><i class="fa fa-home"></i></a></li>
  <li class="active">Pasajeros</li>
</ol>

<div class="block">
    <div class="block-title">
        <div class="block-options pull-right">
            <a href="#modal-nuevo" class="btn btn-sm btn-primary" data-toggle="modal" data-toggle="tooltip" title="Agregar Vehículo"><i class="fa fa-plus"></i></a>
        </div>
        <h2 class=""><i class="gi gi-parents"></i> <strong>Pasajeros</strong></h2>  
    </div>
    <div class="table-responsive">
        <table class="table table-bordered center">
        	<thead>	
        			<th>No.</th>
        	        <th>DOCUMENTO</th>
        	        <th>APELLIDOS</th>
        	        <th>NOMBRES</th>
        	        <th>DIRECCI&Oacute;N</th>
        	        <th>TEL&Eacute;FONO</th>
                    <th></th>
        	</thead>

        	<?php for($i = 0; $i < count($this->pasajeros); $i++): ?>
            
            <tr>
            	<td><?php echo ($i+1); ?></td>
                <td><?php echo $this->pasajeros[$i]['cedula']; ?></td>
                <td><?php echo $this->pasajeros[$i]['apellidos']; ?></td>
                <td><?php echo $this->pasajeros[$i]['nombres']; ?></td>
                <td><?php echo $this->pasajeros[$i]['direccion']; ?></td>
                <td><?php echo $this->pasajeros[$i]['telefono']; ?></td>
                <td class="text-center">
                    <div class="btn-group btn-group-xs">
                        <a href="<?php echo BASE_URL.'pasajeros/editar/'.$this->pasajeros[$i]['id']; ?>" class="btn btn-warning" data-toggle="tooltip" title="Editar"><i class="fa fa-pencil"></i></a>
                    </div>
                </td>
            </tr>
            
            <?php endfor;?>
        </table>
    </div>
</div>



<!--  Modal -->
 <a href="#modal-nuevo" class="btn btn-primary btn-xs" data-toggle="modal" title="Agregar">Agregar Pasajero</a>
        
        <div id="modal-nuevo" class="modal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    <form action="" method="post" class="">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h3 class="modal-title">Agregar Pasajero</h3>
                        </div>


                    <div class="modal-body form-horizontal form-bordered">
                        <div class="form-group ">
                            <label class="col-md-3 control-label" for="cedula">C&eacute;dula:</label>
                                <div class="col-md-9">
                                 <input class="form-control" type="text" name="cedula" value="<?php if(isset($this->datos)) echo $this->datos['cedula']; ?>" required />
                                </div>
                        
                            <label class="col-md-3 control-label" for="nombres">Nombres:</label>
                                <div class="col-md-9">
                                <input class="form-control" type="text" name="nombres" value="<?php if(isset($this->datos)) echo $this->datos['nombres']; ?>" required />
                                </div>

                             <label class="col-md-3 control-label" for="apellidos">Apellidos:</label>
                                <div class="col-md-9">
                                <input class="form-control" type="text" name="apellidos" value="<?php if(isset($this->datos)) echo $this->datos['apellidos']; ?>" required />
                                </div> 

                            <label class="col-md-3 control-label" for="direccion">Direcci&oacute;n:</label>
                                <div class="col-md-9">
                                 <input class="form-control" type="text" name="direccion" value="<?php if(isset($this->datos)) echo $this->datos['direccion']; ?>"  />
                                </div> 

                            <label class="col-md-3 control-label" for="telefono">Tel&eacute;fono:</label>
                                <div class="col-md-9">
                                 <input class="form-control" type="text" name="telefono" value="<?php if(isset($this->datos)) echo $this->datos['telefono']; ?>"  />
                                </div>

                        </div>
                    </div>
                              
                     <div class="modal-footer">
                        <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Cerrar</button>
                        <button id="btn_nuevo_pasajero" name="guardar" type="submit" class="btn btn-sm btn-primary" >Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- END Modal -->