<ol class="breadcrumb breadcrumb-top">
  <li><a href="<?php echo BASE_URL; ?>"><i class="fa fa-home"></i></a></li>
  <li class="active">Tarjetas de Operación</li>
</ol>

<div class="panel panel-default">
	<div class="panel-heading"><strong>Tarjetas de Operación </strong>
		&nbsp; &nbsp; &nbsp; 
		<a class="btn btn-primary btn-xs" href="<?php echo BASE_URL; ?>tarjeta_operacion/nuevo">Agregar Tarjeta de Operación</a>
	</div>
    <table class="table table-bordered center">
    	<thead>	
    			<th>No.</th>
    			<th>AUTOMOTOR</th>
    	        <th>TARJETA</th>
    	        <th>CAPACIDAD</th>
    	        <th>FEC. EXPEDICI&Oacute;N</th>
    	        <th>FEC. VENCIMIENTO</th>
                <th></th>
    	</thead>

    	<?php for($i = 0; $i < count($this->tarjetas); $i++): ?>
    	<?php $diferencia = date_diff(date_create(date("Y-m-d")), date_create($this->tarjetas[$i]['fec_vencimiento']))->format('%R%a'); ?>
        <?php if ($diferencia <= -15): ?>
        	<tr class="active">
        <?php elseif ($diferencia <= 30): ?>
        	<tr class="danger">
        <?php else: ?>
			 <tr class="success">
        <?php endif ?>
       
        	<td><?php echo ($i+1); ?></td>
        	<td><?php echo $this->tarjetas[$i]['numero']." - ".$this->tarjetas[$i]['placa']; ?></td>
            <td><?php echo $this->tarjetas[$i]['tarjeta']; ?></td>
            <td><?php echo $this->tarjetas[$i]['capacidad']; ?></td>
            <td><?php echo $this->tarjetas[$i]['fec_expedicion']; ?></td>
            <td><?php echo $this->tarjetas[$i]['fec_vencimiento']; ?></td>
            
            <td><a href="<?php echo BASE_URL.'tarjeta_operacion/editar/'.$this->tarjetas[$i]['id']; ?>">Editar</a></td>
        </tr>
        
        <?php endfor;?>
    </table>
</div>