<ol class="breadcrumb breadcrumb-top">
  <li><a href="<?php echo BASE_URL; ?>"><i class="fa fa-home"></i></a></li>
  <li><a href="<?php echo BASE_URL ?>tarjeta_operacion">Tarjetas de Operación</a></li>
  <li class="active">Nueva</li>
</ol>

<h2>NUEVA TARJETA DE OPERACIÓN</h2>

<form name="form1" method="post" action="">
    <input type="hidden" value="1" name="guardar" />
    <div class="row">
        <div class="col-md-4">
            <div class="">
                <div class="form-group">
                    <label>No. Vehiculo: </label>
                    <select class="form-control" name="automotor">
                    	<?php if (isset($this->datos)): ?>
                    		<?php for($i = 0; $i < count($this->automotores); $i++): ?>
                    			<?php if ($this->datos['automotor'] == $i): ?>
                    				<option value="<?php echo $this->automotores[$i]['id']; ?>" selected><?php echo $this->automotores[$i]['numero']." - ".$this->automotores[$i]['placa']; ?></option>
                    			<?php else: ?>
	                            	<option value="<?php echo $this->automotores[$i]['id']; ?>"><?php echo $this->automotores[$i]['numero']." - ".$this->automotores[$i]['placa']; ?></option>
	                            <?php endif ?>
	                        <?php endfor; ?>
	                    <?php else: ?>
	                    	<option value="0" disabled selected>Seleccione...</option>
	                        <?php for($i = 0; $i < count($this->automotores); $i++): ?>
	                            <option value="<?php echo $this->automotores[$i]['id']; ?>"><?php echo $this->automotores[$i]['numero']." - ".$this->automotores[$i]['placa']; ?></option>
	                        <?php endfor; ?>
                    	<?php endif ?>
                    </select>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="">
                <div class="form-group">
                    <label>No. Tarjeta: </label>
                    <input class="form-control" type="text" name="tarjeta" value="<?php if(isset($this->datos)) echo $this->datos['tarjeta']; ?>" placeholder="Número de tarjeta" required />
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="">
                <div class="form-group">
                    <label>Capacidad: </label>
                    <input class="form-control" type="number" name="capacidad" value="<?php if(isset($this->datos)) echo $this->datos['capacidad']; ?>" placeholder="Número de pasajeros" required />
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="">
                <div class="form-group">
                    <label>Fecha expedici&oacute;n: </label>
                    <input type="date" class="form-control" name="fec_expedicion" value="<?php if(isset($this->datos)) echo $this->datos['fec_expedicion']; ?>" required>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="">
                <div class="form-group">
                    <label>Fecha Vencimiento: </label>
                    <input type="date" class="form-control" name="fec_vencimiento" value="<?php if(isset($this->datos)) echo $this->datos['fec_vencimiento']; ?>" required>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="">
                <div class="form-group">
                    <input class="btn btn-primary" type="submit" value="Guardar" />
                </div>
            </div>
        </div>
    </div>
</form>

<br><br>