<ol class="breadcrumb breadcrumb-top">
  <li><a href="<?php echo BASE_URL; ?>"><i class="fa fa-home"></i></a></li>
  <li class="active">Revisión Tecnomecánica</li>
</ol>

<div class="block">
    <div class="block-title">
        <div class="block-options pull-right">
            <a href="#modal-nuevo" class="btn btn-sm btn-primary" data-toggle="modal" title="Agregar"><i class="fa fa-plus"></i></a>
        </div>
        <h2 class=""><i class="hi hi-wrench"></i> <strong>Certificados</strong></h2>
        <!--<a href="#modal-nuevo" class="btn btn-primary btn-xs" data-toggle="modal" title="Agregar">Agregar Vehiculo</a>-->
    </div>

    <table class="table table-bordered center">
    	<thead>	
			<th>No.</th>
            <th>VEHÍCULO</th>
			<th>REVISIÓN</th>
	        <th>FEC. DE EXPEDICIÓN</th>
	        <th>FEC. VENCIMIENTO</th>
            <th></th>
    	</thead>

    	<?php for($i = 0; $i < count($this->tecnomecanicas); $i++): ?>
        	<?php $diferencia = date_diff(date_create(date("Y-m-d")), date_create($this->tecnomecanicas[$i]['fec_vencimiento']))->format('%R%a'); ?>
            <?php if ($diferencia <= -15): ?>
            	<tr class="active">
            <?php elseif ($diferencia <= 30): ?>
            	<tr class="danger">
            <?php else: ?>
    			 <tr class="success">
            <?php endif ?>
       
            	<td><?php echo ($i+1); ?></td>
            	<td><?php echo $this->tecnomecanicas[$i]['numero']." - ".$this->tecnomecanicas[$i]['placa']; ?></td>
                <td><?php echo $this->tecnomecanicas[$i]['consecutivo']; ?></td>
                <td><?php echo $this->tecnomecanicas[$i]['fec_expedicion']; ?></td>
                <td><?php echo $this->tecnomecanicas[$i]['fec_vencimiento']; ?></td>
                <td class="text-center">
                    <div class="btn-group btn-group-xs">
                        <a href="<?php echo BASE_URL.'tecnomecanica/editar/'.$this->tecnomecanicas[$i]['id']; ?>" class="btn btn-warning" data-toggle="tooltip" title="Editar"><i class="gi gi-pencil"></i></a>
                    </div>
                </td>
            </tr>
        
        <?php endfor;?>
    </table>
</div>


<!--  Modal nueva tecnomecanica-->
<div id="modal-nuevo" class="modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <form action="" method="post" class="">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3 class="modal-title">Agregar Revisión Tecnomecánica</h3>
                </div>


                <div class="modal-body form-horizontal form-bordered">
                    <div class="form-group ">
                        <label class="col-md-3 control-label" for="numero0">Vehículo:</label>
                        <div class="col-md-8">
                            <select name="automotor" class="select-chosen" data-placeholder="Seleccione.." style="width: 250px;">
                                <option></option>
                                <?php for($i = 0; $i < count($this->automotores); $i++): ?>
                                    <option value="<?php echo $this->automotores[$i]['id']; ?>"><?php echo $this->automotores[$i]['numero']." - ".$this->automotores[$i]['placa']; ?></option>
                                <?php endfor; ?>
                            </select>
                        </div>
                
                        <label class="col-md-3 control-label" for="placa0">No.Revisión:</label>
                        <div class="col-md-8">
                            <input class="form-control" title="Se necesita el numero de revision" type="text" name="consecutivo" value="<?php if(isset($this->datos)) echo $this->datos['tecno']; ?>" maxlength="20" required />
                        </div>

                        <label class="col-md-3 control-label" for="fec_expedicion">Vigencia</label>
                        <div class="col-md-8">
                            <div class="input-group input-daterange" data-date-format="yyyy/mm/dd">
                                <input type="text" id="fec_expedicion" name="fec_expedicion" class="form-control text-center" placeholder="Expedición">
                                <span class="input-group-addon"><i class="fa fa-angle-right"></i></span>
                                <input type="text" id="fec_vencimiento" name="fec_vencimiento" class="form-control text-center" placeholder="Vencimiento">
                            </div>
                        </div>    
                    </div>
                </div>
                      
                <div class="modal-footer">
                    <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Cerrar</button>
                    <button type="button" id="btn_nuevo_tecnomecanica" class="btn btn-sm btn-primary" data-dismiss="modal">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Fin Modal nueva tecnomecanica -->
