<div class="row">
    <div class="col-sm-12 col-md-3 col-lg-3">
        <div class="block">
            <div class="block-title">
                <div class="block-options pull-right btn-group btn-group-xs">
                    <a href="#modal-rol" class="btn btn-xs btn-default" data-toggle="modal" title="Ver"><i class="gi gi-plus"></i></a>
                </div>
                <h2><i class="fa fa-group"></i> <strong>Roles</strong></h2>
            </div>

            <?php if (isset($this->roles) && count($this->roles)): ?>
            <table class="table table-condensed table-striped">
                
                <?php foreach ($this->roles as $rol): ?>
                    <tr>
                        <td><?php echo $rol['rol']; ?></td>
                        <td>
                            <div class="btn-group btn-group-xs">
                                <a href="<?php echo BASE_URL.'acl/permisos_rol/'. $rol['id']; ?>" class="btn btn-default" data-toggle="tooltip" title="Editar permisos"><i class="fa fa-pencil"></i></a>
                            </div>
                            
                        </td>
                    </tr>
                 <?php endforeach ?>
            </table>
        <?php endif ?>
        </div>
    </div>
</div>

<!-- Rol Modal -->
<div id="modal-rol" class="modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <form action="" method="post" class="">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3 class="modal-title">Nuevo Rol</h3>
                </div>
                <div class="modal-body form-horizontal form-bordered">
                    <div class="form-group ">
                        <label class="col-md-3 control-label" for="rol">Rol</label>
                        <div class="col-md-9">
                            <input type="text" id="rol" name="rol" class="form-control" placeholder="Nombre de rol">
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-sm btn-primary" >Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- END Rol Modal -->


